
import { GoogleGenAI, Type, Modality } from "@google/genai";
import type { AspectRatio, GeneratedContent, ImageStyle, ImageModel } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const postGenerationSchema = {
  type: Type.OBJECT,
  properties: {
    posts: {
      type: Type.ARRAY,
      description: "An array of 2 distinct social media posts written in Egyptian Arabic.",
      items: { type: Type.STRING }
    },
    imagePrompt: {
      type: Type.STRING,
      description: "A detailed, creative prompt in English for an AI image generator to create a suitable visual for the posts."
    }
  },
  required: ["posts", "imagePrompt"]
};

export const generatePosts = async (prompt: string, trainingText: string, postGoal: string, activityField: string): Promise<GeneratedContent> => {
  const model = "gemini-2.5-pro";
  
  const systemInstruction = `You are a world-class social media content creator specializing in the Egyptian market.
- Your primary language is Egyptian Arabic.
- You will be given a post idea, a post goal, the page's activity field, and, optionally, examples of a user's writing style.
- Your task is to generate 2 distinct, engaging social media posts based on all the provided information.
- The generated posts must align with the specified 'Post Goal' (e.g., sales, educational).
- The content should be relevant to the 'Page Activity/Field'.
- By default, your writing style must be simple and direct, without exaggeration.
- If training text is provided, you must adapt your tone and style to match it perfectly.
- You must also provide a detailed image generation prompt in English that visually represents the core message of the posts.
- You must respond only with a valid JSON object matching the provided schema.`;

  const fullPrompt = `
Post Goal: ${postGoal}
Page Activity/Field: ${activityField || 'General'}

Here is the user's post idea:
---
${prompt}
---

${trainingText ? `
Here are examples of the user's writing style. Adapt to this style:
---
${trainingText}
---
` : ''}

Generate the 2 posts and the image prompt.
`;

  try {
    const response = await ai.models.generateContent({
      model,
      contents: fullPrompt,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema: postGenerationSchema,
        temperature: 0.8,
      },
    });

    const text = response.text;
    const parsedResult = JSON.parse(text);

    if (!parsedResult.posts || !parsedResult.imagePrompt || parsedResult.posts.length < 2) {
        throw new Error("Invalid response structure from API.");
    }
    
    return parsedResult as GeneratedContent;

  } catch (error) {
    console.error("Error generating posts:", error);
    throw new Error("Failed to generate posts from Gemini API.");
  }
};

export const generateImage = async (prompt: string, style: ImageStyle, aspectRatio: AspectRatio, model: ImageModel): Promise<string> => {
    const fullPrompt = `${prompt}, in the style of ${style}.`;

    try {
        if (model === 'gemini-2.5-flash-image') {
            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash-image',
                contents: { parts: [{ text: fullPrompt }] },
                config: {
                    responseModalities: [Modality.IMAGE],
                },
            });

            const imagePart = response.candidates?.[0]?.content?.parts?.find(part => part.inlineData);
            if (imagePart?.inlineData) {
                return imagePart.inlineData.data;
            } else {
                throw new Error("No image data found in gemini-2.5-flash-image response.");
            }
        } else { // Default to 'imagen-4.0-generate-001'
            const response = await ai.models.generateImages({
                model: 'imagen-4.0-generate-001',
                prompt: fullPrompt,
                config: {
                    numberOfImages: 1,
                    outputMimeType: 'image/jpeg',
                    aspectRatio: aspectRatio,
                },
            });

            if (response.generatedImages && response.generatedImages.length > 0) {
                return response.generatedImages[0].image.imageBytes;
            } else {
                throw new Error("No image was generated by Imagen.");
            }
        }
    } catch (error) {
        console.error("Error generating image:", error);
        throw new Error("Failed to generate image from API.");
    }
};

export const refinePost = async (postText: string, instruction: string): Promise<string> => {
  const model = "gemini-2.5-pro";

  const systemInstruction = `You are an expert social media copy editor specializing in the Egyptian market. 
Your task is to refine the given text based on the user's instruction. 
You must only output the refined Egyptian Arabic text, with no extra formatting, introductory phrases, or explanations.`;
  
  const fullPrompt = `Please refine the following post.
Instruction: "${instruction}"

Original Post:
---
${postText}
---

Refined Post:`;

  try {
    const response = await ai.models.generateContent({
      model,
      contents: fullPrompt,
      config: {
        systemInstruction,
        temperature: 0.7,
      },
    });

    const text = response.text.trim();
    if (!text) {
        throw new Error("API returned an empty response.");
    }
    return text;

  } catch (error) {
    console.error("Error refining post:", error);
    throw new Error("Failed to refine post from Gemini API.");
  }
};

export const generatePostIdeas = async (interests: string[]): Promise<string[]> => {
    const model = "gemini-2.5-flash"; // Flash is good for this kind of quick task
    
    const systemInstruction = `You are a creative assistant specializing in social media content ideas for the Egyptian market. 
    - Your responses must be in Egyptian Arabic.
    - You will generate 5 distinct, engaging, and brief post ideas based on the user's selected interests.
    - You must respond only with a valid JSON array of strings.`;

    const fullPrompt = `Please generate 5 social media post ideas based on these interests: ${interests.join(', ')}.`;

    const postIdeasSchema = {
        type: Type.ARRAY,
        description: "An array of 5 social media post ideas in Egyptian Arabic.",
        items: { type: Type.STRING }
    };

    try {
        const response = await ai.models.generateContent({
            model,
            contents: fullPrompt,
            config: {
                systemInstruction,
                responseMimeType: "application/json",
                responseSchema: postIdeasSchema,
                temperature: 0.9,
            },
        });

        const text = response.text;
        const parsedResult = JSON.parse(text);

        if (!Array.isArray(parsedResult) || parsedResult.length === 0) {
            throw new Error("Invalid response structure from API. Expected a JSON array of strings.");
        }
        
        return parsedResult as string[];

    } catch (error) {
        console.error("Error generating post ideas:", error);
        throw new Error("Failed to generate post ideas from Gemini API.");
    }
};